<?php
/**
 * CustomerInvoiceRowApiTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma eAccounting API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CustomerInvoiceRowApiTest Class Doc Comment
 *
 * @category    Class
 * @description CustomerInvoiceRowApi
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerInvoiceRowApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerInvoiceRowApi"
     */
    public function testCustomerInvoiceRowApi()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "article_number"
     */
    public function testPropertyArticleNumber()
    {
    }

    /**
     * Test attribute "article_id"
     */
    public function testPropertyArticleId()
    {
    }

    /**
     * Test attribute "amount_no_vat"
     */
    public function testPropertyAmountNoVat()
    {
    }

    /**
     * Test attribute "percent_vat"
     */
    public function testPropertyPercentVat()
    {
    }

    /**
     * Test attribute "line_number"
     */
    public function testPropertyLineNumber()
    {
    }

    /**
     * Test attribute "is_text_row"
     */
    public function testPropertyIsTextRow()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "unit_price"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "unit_abbreviation"
     */
    public function testPropertyUnitAbbreviation()
    {
    }

    /**
     * Test attribute "unit_abbreviation_english"
     */
    public function testPropertyUnitAbbreviationEnglish()
    {
    }

    /**
     * Test attribute "discount_percentage"
     */
    public function testPropertyDiscountPercentage()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "is_work_cost"
     */
    public function testPropertyIsWorkCost()
    {
    }

    /**
     * Test attribute "is_vat_free"
     */
    public function testPropertyIsVatFree()
    {
    }

    /**
     * Test attribute "cost_center_item_id1"
     */
    public function testPropertyCostCenterItemId1()
    {
    }

    /**
     * Test attribute "cost_center_item_id2"
     */
    public function testPropertyCostCenterItemId2()
    {
    }

    /**
     * Test attribute "cost_center_item_id3"
     */
    public function testPropertyCostCenterItemId3()
    {
    }

    /**
     * Test attribute "unit_id"
     */
    public function testPropertyUnitId()
    {
    }

    /**
     * Test attribute "project_id"
     */
    public function testPropertyProjectId()
    {
    }

    /**
     * Test attribute "work_cost_type"
     */
    public function testPropertyWorkCostType()
    {
    }

    /**
     * Test attribute "work_hours"
     */
    public function testPropertyWorkHours()
    {
    }

    /**
     * Test attribute "material_costs"
     */
    public function testPropertyMaterialCosts()
    {
    }

    /**
     * Test attribute "green_technology_type"
     */
    public function testPropertyGreenTechnologyType()
    {
    }
}
