<?php
/**
 * DirectDebitCustomerSettingsApiTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Struqtur\VismaEAccounting
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma eAccounting API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.41
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Struqtur\VismaEAccounting;

/**
 * DirectDebitCustomerSettingsApiTest Class Doc Comment
 *
 * @category    Class
 * @description DirectDebitCustomerSettingsApi
 * @package     Struqtur\VismaEAccounting
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DirectDebitCustomerSettingsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DirectDebitCustomerSettingsApi"
     */
    public function testDirectDebitCustomerSettingsApi()
    {
    }

    /**
     * Test attribute "mandate_id"
     */
    public function testPropertyMandateId()
    {
    }

    /**
     * Test attribute "mandate_type"
     */
    public function testPropertyMandateType()
    {
    }

    /**
     * Test attribute "sequence_type"
     */
    public function testPropertySequenceType()
    {
    }

    /**
     * Test attribute "signing_date"
     */
    public function testPropertySigningDate()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "latest_direct_debit"
     */
    public function testPropertyLatestDirectDebit()
    {
    }
}
