<?php
/**
 * IEdmNavigationPropertyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma eAccounting API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * IEdmNavigationPropertyTest Class Doc Comment
 *
 * @category    Class
 * @description IEdmNavigationProperty
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IEdmNavigationPropertyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IEdmNavigationProperty"
     */
    public function testIEdmNavigationProperty()
    {
    }

    /**
     * Test attribute "partner"
     */
    public function testPropertyPartner()
    {
    }

    /**
     * Test attribute "on_delete"
     */
    public function testPropertyOnDelete()
    {
    }

    /**
     * Test attribute "contains_target"
     */
    public function testPropertyContainsTarget()
    {
    }

    /**
     * Test attribute "referential_constraint"
     */
    public function testPropertyReferentialConstraint()
    {
    }

    /**
     * Test attribute "property_kind"
     */
    public function testPropertyPropertyKind()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "declaring_type"
     */
    public function testPropertyDeclaringType()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }
}
