<?php
/**
 * InventoryAccumulatedDepreciationApiTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Struqtur\VismaEAccounting
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma eAccounting API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.41
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Struqtur\VismaEAccounting;

/**
 * InventoryAccumulatedDepreciationApiTest Class Doc Comment
 *
 * @category    Class
 * @description InventoryAccumulatedDepreciationApi
 * @package     Struqtur\VismaEAccounting
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InventoryAccumulatedDepreciationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InventoryAccumulatedDepreciationApi"
     */
    public function testInventoryAccumulatedDepreciationApi()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "fiscal_year_id"
     */
    public function testPropertyFiscalYearId()
    {
    }

    /**
     * Test attribute "opening_accumulated_depreciation"
     */
    public function testPropertyOpeningAccumulatedDepreciation()
    {
    }

    /**
     * Test attribute "depreciation_for_the_year"
     */
    public function testPropertyDepreciationForTheYear()
    {
    }
}
