<?php
/**
 * SupplierInvoiceDraftApiTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma eAccounting API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SupplierInvoiceDraftApiTest Class Doc Comment
 *
 * @category    Class
 * @description SupplierInvoiceDraftApi
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SupplierInvoiceDraftApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SupplierInvoiceDraftApi"
     */
    public function testSupplierInvoiceDraftApi()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "supplier_id"
     */
    public function testPropertySupplierId()
    {
    }

    /**
     * Test attribute "bank_account_id"
     */
    public function testPropertyBankAccountId()
    {
    }

    /**
     * Test attribute "invoice_date"
     */
    public function testPropertyInvoiceDate()
    {
    }

    /**
     * Test attribute "payment_date"
     */
    public function testPropertyPaymentDate()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "total_amount"
     */
    public function testPropertyTotalAmount()
    {
    }

    /**
     * Test attribute "vat"
     */
    public function testPropertyVat()
    {
    }

    /**
     * Test attribute "vat_high"
     */
    public function testPropertyVatHigh()
    {
    }

    /**
     * Test attribute "vat_medium"
     */
    public function testPropertyVatMedium()
    {
    }

    /**
     * Test attribute "vat_low"
     */
    public function testPropertyVatLow()
    {
    }

    /**
     * Test attribute "is_credit_invoice"
     */
    public function testPropertyIsCreditInvoice()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "currency_rate"
     */
    public function testPropertyCurrencyRate()
    {
    }

    /**
     * Test attribute "ocr_number"
     */
    public function testPropertyOcrNumber()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "created_utc"
     */
    public function testPropertyCreatedUtc()
    {
    }

    /**
     * Test attribute "modified_utc"
     */
    public function testPropertyModifiedUtc()
    {
    }

    /**
     * Test attribute "rows"
     */
    public function testPropertyRows()
    {
    }

    /**
     * Test attribute "supplier_name"
     */
    public function testPropertySupplierName()
    {
    }

    /**
     * Test attribute "supplier_number"
     */
    public function testPropertySupplierNumber()
    {
    }

    /**
     * Test attribute "self_employed_without_fixed_address"
     */
    public function testPropertySelfEmployedWithoutFixedAddress()
    {
    }

    /**
     * Test attribute "is_quick_invoice"
     */
    public function testPropertyIsQuickInvoice()
    {
    }

    /**
     * Test attribute "is_domestic"
     */
    public function testPropertyIsDomestic()
    {
    }

    /**
     * Test attribute "approval_status"
     */
    public function testPropertyApprovalStatus()
    {
    }

    /**
     * Test attribute "skip_send_to_bank"
     */
    public function testPropertySkipSendToBank()
    {
    }

    /**
     * Test attribute "allocation_periods"
     */
    public function testPropertyAllocationPeriods()
    {
    }

    /**
     * Test attribute "attachments"
     */
    public function testPropertyAttachments()
    {
    }
}
