<?php
/**
 * AccountsV2ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma eAccounting API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AccountsV2ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountsV2ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for accountsV2Get
     *
     * Get a list of accounts.
     *
     */
    public function testAccountsV2Get()
    {
    }

    /**
     * Test case for accountsV2Get_0
     *
     * Get a list of the predefined standard accounts..
     *
     */
    public function testAccountsV2Get0()
    {
    }

    /**
     * Test case for accountsV2Get_1
     *
     * Get a list of accounts.
     *
     */
    public function testAccountsV2Get1()
    {
    }

    /**
     * Test case for accountsV2Get_2
     *
     * Get a account.
     *
     */
    public function testAccountsV2Get2()
    {
    }

    /**
     * Test case for accountsV2Post
     *
     * Add a account.
     *
     */
    public function testAccountsV2Post()
    {
    }

    /**
     * Test case for accountsV2Put
     *
     * Replace a account.
     *
     */
    public function testAccountsV2Put()
    {
    }
}
