<?php
/**
 * CustomerLedgerItemsV2ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma eAccounting API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CustomerLedgerItemsV2ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomerLedgerItemsV2ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for customerLedgerItemsV2Get
     *
     * Get a list of customer ledger items..
     *
     */
    public function testCustomerLedgerItemsV2Get()
    {
    }

    /**
     * Test case for customerLedgerItemsV2Get_0
     *
     * Get a customer ledger item by id..
     *
     */
    public function testCustomerLedgerItemsV2Get0()
    {
    }

    /**
     * Test case for customerLedgerItemsV2Post
     *
     * Create a customer ledger item..
     *
     */
    public function testCustomerLedgerItemsV2Post()
    {
    }

    /**
     * Test case for customerLedgerItemsV2Post_0
     *
     * Create a customer ledger item and a voucher included..
     *
     */
    public function testCustomerLedgerItemsV2Post0()
    {
    }
}
