<?php
/**
 * CustomersV2ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma eAccounting API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CustomersV2ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomersV2ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for customersV2Delete
     *
     * Delete a customer..
     *
     */
    public function testCustomersV2Delete()
    {
    }

    /**
     * Test case for customersV2Get
     *
     * Get all customers..
     *
     */
    public function testCustomersV2Get()
    {
    }

    /**
     * Test case for customersV2GetAutoInvoiceRecipients
     *
     * Check this list if the provided customer can receive e-invoices. An empty list is retrieved if the customer   is a private person or is not found in the network..
     *
     */
    public function testCustomersV2GetAutoInvoiceRecipients()
    {
    }

    /**
     * Test case for customersV2Get_0
     *
     * Get a specific customer..
     *
     */
    public function testCustomersV2Get0()
    {
    }

    /**
     * Test case for customersV2Post
     *
     * Creates a customer..
     *
     */
    public function testCustomersV2Post()
    {
    }

    /**
     * Test case for customersV2Put
     *
     * Replace the data in a customer..
     *
     */
    public function testCustomersV2Put()
    {
    }
}
