<?php
/**
 * FiscalYearsV2ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma eAccounting API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * FiscalYearsV2ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FiscalYearsV2ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for fiscalYearsV2Get
     *
     * Get a list of fiscal years..
     *
     */
    public function testFiscalYearsV2Get()
    {
    }

    /**
     * Test case for fiscalYearsV2Get_0
     *
     * Get a single fiscal year..
     *
     */
    public function testFiscalYearsV2Get0()
    {
    }

    /**
     * Test case for fiscalYearsV2Get_1
     *
     * Gets the opening balances of the first fiscal year. If you want balances of following years, use the GET /accountbalances instead..
     *
     */
    public function testFiscalYearsV2Get1()
    {
    }

    /**
     * Test case for fiscalYearsV2Post
     *
     * Create a fiscal year..
     *
     */
    public function testFiscalYearsV2Post()
    {
    }

    /**
     * Test case for fiscalYearsV2UpdateAccountOpeningBalance
     *
     * Updates the opening balance of the first fiscal year.
     *
     */
    public function testFiscalYearsV2UpdateAccountOpeningBalance()
    {
    }
}
