<?php
/**
 * OrdersV2ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma eAccounting API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * OrdersV2ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrdersV2ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for ordersV2BackOrder
     *
     * .
     *
     */
    public function testOrdersV2BackOrder()
    {
    }

    /**
     * Test case for ordersV2Convert
     *
     * Converts an order to an invoice.
     *
     */
    public function testOrdersV2Convert()
    {
    }

    /**
     * Test case for ordersV2Delete
     *
     * Delete an order..
     *
     */
    public function testOrdersV2Delete()
    {
    }

    /**
     * Test case for ordersV2DeliveryNotePrint
     *
     * Get a pdf-file of a delivery note for an order..
     *
     */
    public function testOrdersV2DeliveryNotePrint()
    {
    }

    /**
     * Test case for ordersV2Get
     *
     * Get orders..
     *
     */
    public function testOrdersV2Get()
    {
    }

    /**
     * Test case for ordersV2Get_0
     *
     * Get order.
     *
     */
    public function testOrdersV2Get0()
    {
    }

    /**
     * Test case for ordersV2Post
     *
     * Create order..
     *
     */
    public function testOrdersV2Post()
    {
    }

    /**
     * Test case for ordersV2Print
     *
     * Get a pdf-file of an order..
     *
     */
    public function testOrdersV2Print()
    {
    }

    /**
     * Test case for ordersV2Put
     *
     * Replace content in an order..
     *
     */
    public function testOrdersV2Put()
    {
    }
}
